#!/usr/bin/env bash

echo "Running gradlew build..."
cd backend
./gradlew clean check > $OUTPUT
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0]; then
  cat $OUTPUT
  echo "**********************************************"
  echo "**************** Build Failed ****************"
  echo " Please fix the above issues before committing "
  echo "**********************************************"
  exit $EXIT_CODE
fi
