export enum PipelineTool {
	BAMBOO = "BAMBOO",
	JENKINS = "JENKINS",
	GITHUB_ACTIONS = "GITHUB_ACTIONS",
	BAMBOO_DEPLOYMENT = "BAMBOO_DEPLOYMENT",
	AZURE_PIPELINES = "AZURE_PIPELINES",
	BUDDY = "BUDDY",
}
